# -*- coding: utf-8 -*-
"""02_logreg_Iacobuzio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118k_afWXMrZc-XCbS2V07sOWHybQcAD8
"""

import argparse
import numpy as np

SEED = 676
N_PER_CLASS = 150
CLASS0_CENTER = np.array([-1.3, -0.7])
CLASS1_CENTER = np.array([1.4, 0.9])
SPREAD = 1.1

LEARNING_RATE = 0.15
N_ITERATIONS = 3000

def make_data(rng):

    X0 = rng.normal(CLASS0_CENTER, SPREAD, size=(N_PER_CLASS, 2))
    X1 = rng.normal(CLASS1_CENTER, SPREAD, size=(N_PER_CLASS, 2))
    X = np.vstack([X0, X1])
    y = np.concatenate([np.zeros(N_PER_CLASS), np.ones(N_PER_CLASS)])

    order = rng.permutation(len(y))       # shuffle so class order carries no signal
    return X[order], y[order]

def add_intercept(X):
    return np.hstack([np.ones((X.shape[0], 1)), X])

def sigma(z):
  return 1 / (1 + np.exp(-z))

def predict_proba(X_design, beta):
    """P(y = 1 | x) for every row."""
    return sigma(X_design @ beta)

def predict_label(X_design, beta, threshold=0.5):
    return (predict_proba(X_design, beta) >= threshold).astype(int)

def log_loss(y, p, eps=1e-12):

    p = np.clip(p, eps, 1 - eps)
    return float(-np.mean(y * np.log(p) + (1 - y) * np.log(1 - p)))

def gradient(X_design, y, beta):

    n = X_design.shape[0]
    return X_design.T @ (predict_proba(X_design, beta) - y) / n

def fit_gradient_descent(X_design, y, lr=LEARNING_RATE, n_iter=N_ITERATIONS):

    beta = np.zeros(X_design.shape[1])
    history = []



def fit_gradient_descent(X_design, y, lr=LEARNING_RATE, n_iter=N_ITERATIONS):

    beta = np.zeros(X_design.shape[1])
    history = []

    for _ in range(n_iter):
        p = predict_proba(X_design, beta)
        history.append(log_loss(y, p))
        grad = gradient(X_design, y, beta)
        beta = beta - lr * grad

    return beta, history

def confusion(y_true, y_pred):
    """Return (tn, fp, fn, tp) — the four ways a binary prediction can land."""
    tn = int(np.sum((y_true == 0) & (y_pred == 0)))
    fp = int(np.sum((y_true == 0) & (y_pred == 1)))
    fn = int(np.sum((y_true == 1) & (y_pred == 0)))
    tp = int(np.sum((y_true == 1) & (y_pred == 1)))
    return tn, fp, fn, tp

def metrics(y_true, y_pred):
    tn, fp, fn, tp = confusion(y_true, y_pred)
    acc = (tp + tn) / len(y_true)
    prec = tp / (tp + fp) if (tp + fp) else 0.0
    rec = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * prec * rec / (prec + rec) if (prec + rec) else 0.0
    return {"accuracy": acc, "precision": prec, "recall": rec, "f1": f1,
            "tn": tn, "fp": fp, "fn": fn, "tp": tp}

def report(beta, history, y, y_hat, p):
    m = metrics(y, y_hat)
    print("=" * 62)
    print("  LOGISTIC REGRESSION — gradient descent on the log-loss")
    print("=" * 62)
    print(f"\n  coefficients: intercept={beta[0]:+.4f}  x1={beta[1]:+.4f}  x2={beta[2]:+.4f}")
    print(f"  iterations   : {len(history)}")
    print(f"  log-loss     : {history[0]:.4f} -> {history[-1]:.4f}")

    print("\n  confusion matrix")
    print("                 pred 0   pred 1")
    print(f"      true 0  {m['tn']:>8}{m['fp']:>9}")
    print(f"      true 1  {m['fn']:>8}{m['tp']:>9}")

    print(f"\n  accuracy  {m['accuracy']:.4f}")
    print(f"  precision {m['precision']:.4f}")
    print(f"  recall    {m['recall']:.4f}")
    print(f"  f1        {m['f1']:.4f}")

    # A model that only ever guessed the majority class would score this:
    baseline = max(np.mean(y), 1 - np.mean(y))
    print(f"\n  majority-class baseline: {baseline:.4f}   <- you must beat this")
    verdict = "PASS" if m["accuracy"] > baseline else "NO BETTER THAN GUESSING — check the loop"
    print(f"  [{verdict}]")
    print("=" * 62)
    return m, baseline

def save_plot(X, y, beta, history, path="02_logreg_fit.png"):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("  [plot skipped — pip install matplotlib]")
        return None

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.4))
    # Decision boundary: the line where beta0 + beta1*x1 + beta2*x2 = 0
    xs = np.linspace(X[:, 0].min() - 0.5, X[:, 0].max() + 0.5, 200)
    if abs(beta[2]) > 1e-9:
        ax1.plot(xs, -(beta[0] + beta[1] * xs) / beta[2], color="black", lw=2,
                 label="decision boundary")
    ax1.scatter(X[y == 0, 0], X[y == 0, 1], s=16, alpha=0.6, label="class 0")
    ax1.scatter(X[y == 1, 0], X[y == 1, 1], s=16, alpha=0.6, label="class 1")
    ax1.set_xlabel("x1"); ax1.set_ylabel("x2"); ax1.set_title("Data and boundary"); ax1.legend()

    ax2.plot(history, lw=1.6)
    ax2.set_xlabel("iteration"); ax2.set_ylabel("log-loss"); ax2.set_title("Loss curve")

    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print(f"  [plot saved -> {path}]")
    return path

def save_report(beta, history, m, baseline, path="02_logreg_report.md"):
    text = f"""# Homework 02 — Logistic Regression

Fitted {2 * N_PER_CLASS} observations (two overlapping Gaussian blobs) by batch
gradient descent on the log-loss, learning rate {LEARNING_RATE},
{len(history)} iterations.

## Model

| term | coefficient |
| --- | --- |
| intercept | {beta[0]:+.4f} |
| x1 | {beta[1]:+.4f} |
| x2 | {beta[2]:+.4f} |

## Confusion matrix

| | predicted 0 | predicted 1 |
| --- | --- |
| **actual 0** | {m['tn']} | {m['fp']} |
| **actual 1** | {m['fn']} | {m['tp']} |

## Metrics

| metric | value |
| --- | --- |
| accuracy | {m['accuracy']:.4f} |
| precision | {m['precision']:.4f} |
| recall | {m['recall']:.4f} |
| f1 | {m['f1']:.4f} |
| majority-class baseline | {baseline:.4f} |
| log-loss, first iteration | {history[0]:.4f} |
| log-loss, last iteration | {history[-1]:.4f} |
"""

    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  [report saved -> {path}]")
    return path

def main():
    ap = argparse.ArgumentParser(description="Logistic regression from scratch.")
    ap.add_argument("--plot", action="store_true")
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    rng = np.random.default_rng(SEED)
    X, y = make_data(rng)
    X_design = add_intercept(X)

    beta, history = fit_gradient_descent(X_design, y)
    p = predict_proba(X_design, beta)
    y_hat = predict_label(X_design, beta)

    m, baseline = report(beta, history, y, y_hat, p)
    if args.plot:
        save_plot(X, y, beta, history)
    if args.report:
        save_report(beta, history, m, baseline)

import sys

if __name__ == "__main__":
    original_argv = sys.argv
    # Filter out unrecognized arguments that the Colab kernel might pass
    # We keep only the script name and potentially known arguments if the user specified any.
    # For now, we assume no user-specified arguments for the script itself.
    sys.argv = [original_argv[0]]
    try:
        main()
    finally:
        sys.argv = original_argv # Always restore sys.argv to its original state